nutritional_info = {
    "rice": {"protein": 2.7, "carbs": 28, "fat": 0.3},
    "eels on rice": {"protein": 9.6, "carbs": 12, "fat": 5.4},
    "pilaf": {"protein": 3.5, "carbs": 24, "fat": 2.1},
    "chicken-'n'-egg on rice": {"protein": 12.3, "carbs": 20, "fat": 8.6},
    "pork cutlet on rice": {"protein": 14.8, "carbs": 26, "fat": 15},
    "beef curry": {"protein": 10, "carbs": 18, "fat": 12},
    "sushi": {"protein": 4.5, "carbs": 16, "fat": 1.3},
    "chicken rice": {"protein": 8.2, "carbs": 28, "fat": 4.1},
    "fried rice": {"protein": 6.2, "carbs": 30, "fat": 8.7},
    "tempura bowl": {"protein": 11, "carbs": 35, "fat": 14},
    "bibimbap": {"protein": 9, "carbs": 25, "fat": 6},
    "toast": {"protein": 2.7, "carbs": 13, "fat": 1.1},
    "croissant": {"protein": 2.9, "carbs": 27, "fat": 14},
    "roll bread": {"protein": 2.8, "carbs": 26, "fat": 2},
    "raisin bread": {"protein": 3, "carbs": 30, "fat": 1.8},
    "chip butty": {"protein": 4.5, "carbs": 44, "fat": 10},
    "hamburger": {"protein": 14, "carbs": 30, "fat": 15},
    "pizza": {"protein": 11, "carbs": 33, "fat": 12},
    "sandwiches": {"protein": 7, "carbs": 30, "fat": 10},
    "udon noodle": {"protein": 3.5, "carbs": 21, "fat": 0.5},
    "tempura udon": {"protein": 8, "carbs": 35, "fat": 10},
    "soba noodle": {"protein": 5, "carbs": 21, "fat": 1},
    "ramen noodle": {"protein": 6, "carbs": 40, "fat": 10},
    "beef noodle": {"protein": 8, "carbs": 35, "fat": 12},
    "tensin noodle": {"protein": 7, "carbs": 30, "fat": 8},
    "fried noodle": {"protein": 6, "carbs": 35, "fat": 12},
    "spaghetti": {"protein": 5, "carbs": 31, "fat": 1.5},
    "Japanese-style pancake": {"protein": 6, "carbs": 28, "fat": 10},
    "takoyaki": {"protein": 5, "carbs": 26, "fat": 8},
    "gratin": {"protein": 7, "carbs": 15, "fat": 10},
    "sauteed vegetables": {"protein": 2, "carbs": 10, "fat": 3},
    "croquette": {"protein": 4, "carbs": 22, "fat": 8},
    "grilled eggplant": {"protein": 1, "carbs": 5, "fat": 3},
    "sauteed spinach": {"protein": 2.8, "carbs": 3.6, "fat": 2.8},
    "vegetable tempura": {"protein": 3, "carbs": 25, "fat": 12},
    "miso soup": {"protein": 2, "carbs": 5, "fat": 2},
    "potage": {"protein": 2, "carbs": 10, "fat": 5},
    "sausage": {"protein": 12, "carbs": 1, "fat": 10},
    "oden": {"protein": 4, "carbs": 10, "fat": 2},
    "omelet": {"protein": 9, "carbs": 1, "fat": 7},
    "ganmodoki": {"protein": 8, "carbs": 12, "fat": 6},
    "jiaozi": {"protein": 6, "carbs": 25, "fat": 7},
    "stew": {"protein": 6, "carbs": 15, "fat": 5},
    "teriyaki grilled fish": {"protein": 20, "carbs": 5, "fat": 10},
    "fried fish": {"protein": 15, "carbs": 10, "fat": 15},
    "grilled salmon": {"protein": 25, "carbs": 0, "fat": 10},
    "salmon meuniere": {"protein": 23, "carbs": 1, "fat": 12},
    "sashimi": {"protein": 20, "carbs": 0, "fat": 5},
    "grilled pacific saury": {"protein": 20, "carbs": 0, "fat": 10},
    "sukiyaki": {"protein": 15, "carbs": 5, "fat": 10},
    "sweet and sour pork": {"protein": 10, "carbs": 20, "fat": 15},
    "lightly roasted fish": {"protein": 18, "carbs": 0, "fat": 8},
    "steamed egg hotchpotch": {"protein": 6, "carbs": 4, "fat": 5},
    "tempura": {"protein": 12, "carbs": 30, "fat": 15},
    "fried chicken": {"protein": 25, "carbs": 5, "fat": 20},
    "sirloin cutlet": {"protein": 20, "carbs": 15, "fat": 25},
    "nanbanzuke": {"protein": 10, "carbs": 5, "fat": 8},
    "boiled fish": {"protein": 20, "carbs": 2, "fat": 5},
    "seasoned beef with potatoes": {"protein": 15, "carbs": 20, "fat": 15},
    "hambarg steak": {"protein": 20, "carbs": 5, "fat": 15},
    "steak": {"protein": 25, "carbs": 0, "fat": 20},
    "dried fish": {"protein": 25, "carbs": 0, "fat": 5},
    "ginger pork saute": {"protein": 20, "carbs": 5, "fat": 15},
    "spicy chili-flavored tofu": {"protein": 8, "carbs": 5, "fat": 5},
    "yakitori": {"protein": 20, "carbs": 5, "fat": 10},
    "cabbage roll": {"protein": 5, "carbs": 10, "fat": 5},
    "omelet": {"protein": 9, "carbs": 1, "fat": 7},
    "egg sunny-side up": {"protein": 6, "carbs": 1, "fat": 7},
    "natto": {"protein": 8, "carbs": 12, "fat": 5},
    "cold tofu": {"protein": 7, "carbs": 2, "fat": 5},
    "egg roll": {"protein": 9, "carbs": 5, "fat": 8},
    "chilled noodle": {"protein": 4, "carbs": 30, "fat": 2},
    "stir-fried beef and peppers": {"protein": 15, "carbs": 5, "fat": 10},
    "simmered pork": {"protein": 15, "carbs": 5, "fat": 20},
    "boiled chicken and vegetables": {"protein": 20, "carbs": 10, "fat": 5},
    "sashimi bowl": {"protein": 25, "carbs": 40, "fat": 10},
    "sushi bowl": {"protein": 20, "carbs": 50, "fat": 8},
    "fish-shaped pancake with bean jam": {"protein": 4, "carbs": 30, "fat": 5},
    "shrimp with chill source": {"protein": 12, "carbs": 5, "fat": 8},
    "roast chicken": {"protein": 30, "carbs": 0, "fat": 15},
    "steamed meat dumpling": {"protein": 10, "carbs": 20, "fat": 5},
    "omelet with fried rice": {"protein": 10, "carbs": 35, "fat": 10},
    "cutlet curry": {"protein": 15, "carbs": 40, "fat": 20},
    "spaghetti meat sauce": {"protein": 10, "carbs": 35, "fat": 12},
    "fried shrimp": {"protein": 20, "carbs": 10, "fat": 15},
    "potato salad": {"protein": 2, "carbs": 20, "fat": 10},
    "green salad": {"protein": 2, "carbs": 10, "fat": 5},
    "macaroni salad": {"protein": 4, "carbs": 25, "fat": 15},
    "Japanese tofu and vegetable chowder": {"protein": 5, "carbs": 10, "fat": 5},
    "pork miso soup": {"protein": 8, "carbs": 5, "fat": 5},
    "chinese soup": {"protein": 6, "carbs": 5, "fat": 4},
    "beef bowl": {"protein": 15, "carbs": 40, "fat": 20},
    "kinpira-style sauteed burdock": {"protein": 3, "carbs": 10, "fat": 5},
    "rice ball": {"protein": 4, "carbs": 40, "fat": 1},
    "pizza toast": {"protein": 8, "carbs": 25, "fat": 10},
    "dipping noodles": {"protein": 5, "carbs": 40, "fat": 5},
    "hot dog": {"protein": 10, "carbs": 25, "fat": 15},
    "french fries": {"protein": 3, "carbs": 30, "fat": 15},
    "mixed rice": {"protein": 4, "carbs": 30, "fat": 2},
    "goya chanpuru": {"protein": 8, "carbs": 10, "fat": 7},
    "green curry": {"protein": 10, "carbs": 20, "fat": 10},
    "okinawa soba": {"protein": 6, "carbs": 30, "fat": 5},
    "mango pudding": {"protein": 2, "carbs": 20, "fat": 2},
    "almond jelly": {"protein": 2, "carbs": 10, "fat": 3},
    "jjigae": {"protein": 8, "carbs": 5, "fat": 8},
    "dak galbi": {"protein": 20, "carbs": 10, "fat": 15},
    "dry curry": {"protein": 12, "carbs": 35, "fat": 15},
    "kamameshi": {"protein": 6, "carbs": 30, "fat": 3},
    "rice vermicelli": {"protein": 2, "carbs": 45, "fat": 0.5},
    "paella": {"protein": 10, "carbs": 30, "fat": 10},
    "tanmen": {"protein": 5, "carbs": 30, "fat": 5},
    "kushikatu": {"protein": 12, "carbs": 20, "fat": 15},
    "yellow curry": {"protein": 10, "carbs": 25, "fat": 10},
    "pancake": {"protein": 6, "carbs": 50, "fat": 10},
    "champon": {"protein": 10, "carbs": 40, "fat": 15},
    "crape": {"protein": 4, "carbs": 40, "fat": 8},
    "tiramisu": {"protein": 6, "carbs": 40, "fat": 20},
    "waffle": {"protein": 6, "carbs": 50, "fat": 15},
    "rare cheese cake": {"protein": 8, "carbs": 25, "fat": 25},
    "shortcake": {"protein": 5, "carbs": 35, "fat": 20},
    "chop suey": {"protein": 8, "carbs": 20, "fat": 10},
    "twice cooked pork": {"protein": 12, "carbs": 10, "fat": 20},
    "mushroom risotto": {"protein": 5, "carbs": 35, "fat": 10},
    "samul": {"protein": 10, "carbs": 20, "fat": 15},
    "zoni": {"protein": 4, "carbs": 20, "fat": 1},
    "french toast": {"protein": 8, "carbs": 40, "fat": 15},
    "fine white noodles": {"protein": 4, "carbs": 40, "fat": 1},
    "minestrone": {"protein": 5, "carbs": 20, "fat": 5},
    "pot au feu": {"protein": 15, "carbs": 10, "fat": 10},
    "chicken nugget": {"protein": 10, "carbs": 15, "fat": 15},
    "namero": {"protein": 20, "carbs": 0, "fat": 8},
    "french bread": {"protein": 8, "carbs": 50, "fat": 2},
    "rice gruel": {"protein": 1, "carbs": 15, "fat": 0},
    "broiled eel bowl": {"protein": 18, "carbs": 30, "fat": 15},
    "clear soup": {"protein": 2, "carbs": 5, "fat": 1},
    "yudofu": {"protein": 8, "carbs": 2, "fat": 5},
    "mozuku": {"protein": 1, "carbs": 3, "fat": 0.1},
    "inarizushi": {"protein": 5, "carbs": 40, "fat": 3},
    "pork loin cutlet": {"protein": 20, "carbs": 10, "fat": 25},
    "pork fillet cutlet": {"protein": 20, "carbs": 10, "fat": 20},
    "chicken cutlet": {"protein": 25, "carbs": 10, "fat": 15},
    "ham cutlet": {"protein": 15, "carbs": 10, "fat": 20},
    "minced meat cutlet": {"protein": 20, "carbs": 10, "fat": 25},
    "thinly sliced raw horsemeat": {"protein": 30, "carbs": 0, "fat": 5},
    "bagel": {"protein": 10, "carbs": 50, "fat": 2},
    "scone": {"protein": 6, "carbs": 40, "fat": 15},
    "tortilla": {"protein": 4, "carbs": 25, "fat": 2},
    "tacos": {"protein": 10, "carbs": 20, "fat": 10},
    "nachos": {"protein": 8, "carbs": 35, "fat": 20},
    "meat loaf": {"protein": 15, "carbs": 10, "fat": 20},
    "scrambled egg": {"protein": 10, "carbs": 1, "fat": 10},
    "rice gratin": {"protein": 8, "carbs": 30, "fat": 15},
    "lasagna": {"protein": 15, "carbs": 35, "fat": 20},
    "Caesar salad": {"protein": 5, "carbs": 10, "fat": 15},
    "oatmeal": {"protein": 6, "carbs": 27, "fat": 3.6},
    "fried pork dumplings served in soup": {"protein": 8, "carbs": 20, "fat": 10},
    "oshiruko": {"protein": 2, "carbs": 40, "fat": 1},
    "muffin": {"protein": 5, "carbs": 30, "fat": 10},
    "popcorn": {"protein": 3, "carbs": 20, "fat": 10},
    "cream puff": {"protein": 3, "carbs": 20, "fat": 15},
    "doughnut": {"protein": 3, "carbs": 35, "fat": 20},
    "apple pie": {"protein": 2, "carbs": 40, "fat": 15},
    "parfait": {"protein": 5, "carbs": 50, "fat": 20},
    "fried pork in scoop": {"protein": 15, "carbs": 5, "fat": 20},
    "lamb kebabs": {"protein": 25, "carbs": 5, "fat": 20},
    "dish consisting of stir-fried potato, eggplant and green pepper": {"protein": 3, "carbs": 15, "fat": 5},
    "roast duck": {"protein": 20, "carbs": 5, "fat": 25},
    "hot pot": {"protein": 10, "carbs": 10, "fat": 10},
    "pork belly": {"protein": 20, "carbs": 0, "fat": 30},
    "xiao long bao": {"protein": 8, "carbs": 20, "fat": 5},
    "moon cake": {"protein": 5, "carbs": 40, "fat": 20},
    "custard tart": {"protein": 3, "carbs": 30, "fat": 20},
    "beef noodle soup": {"protein": 10, "carbs": 35, "fat": 10},
    "pork cutlet": {"protein": 20, "carbs": 10, "fat": 25},
    "minced pork rice": {"protein": 15, "carbs": 40, "fat": 15},
    "fish ball soup": {"protein": 12, "carbs": 5, "fat": 5},
    "oyster omelette": {"protein": 10, "carbs": 20, "fat": 15},
    "glutinous oil rice": {"protein": 5, "carbs": 40, "fat": 5},
    "trunip pudding": {"protein": 2, "carbs": 20, "fat": 5},
    "stinky tofu": {"protein": 5, "carbs": 3, "fat": 3},
    "lemon fig jelly": {"protein": 0.5, "carbs": 15, "fat": 0.1},
    "khao soi": {"protein": 8, "carbs": 35, "fat": 15},
    "Sour prawn soup": {"protein": 10, "carbs": 5, "fat": 3},
    "Thai papaya salad": {"protein": 2, "carbs": 10, "fat": 5},
    "boned, sliced Hainan-style chicken with marinated rice": {"protein": 15, "carbs": 35, "fat": 10},
    "hot and sour, fish and vegetable ragout": {"protein": 10, "carbs": 5, "fat": 5},
    "stir-fried mixed vegetables": {"protein": 2, "carbs": 15, "fat": 5},
    "beef in oyster sauce": {"protein": 20, "carbs": 10, "fat": 15},
    "pork satay": {"protein": 10, "carbs": 5, "fat": 15},
    "spicy chicken salad": {"protein": 15, "carbs": 5, "fat": 10},
    "noodles with fish curry": {"protein": 8, "carbs": 35, "fat": 10},
    "Pork Sticky Noodles": {"protein": 10, "carbs": 40, "fat": 15},
    "Pork with lemon": {"protein": 20, "carbs": 5, "fat": 10},
    "stewed pork leg": {"protein": 15, "carbs": 5, "fat": 20},
    "charcoal-boiled pork neck": {"protein": 20, "carbs": 0, "fat": 25},
    "fried mussel pancakes": {"protein": 12, "carbs": 20, "fat": 15},
    "Deep Fried Chicken Wing": {"protein": 25, "carbs": 0, "fat": 20},
    "Barbecued red pork in sauce with rice": {"protein": 15, "carbs": 35, "fat": 10},
    "Rice with roast duck": {"protein": 20, "carbs": 35, "fat": 15},
    "Rice crispy pork": {"protein": 15, "carbs": 30, "fat": 20},
    "Wonton soup": {"protein": 8, "carbs": 10, "fat": 5},
    "Chicken Rice Curry With Coconut": {"protein": 15, "carbs": 30, "fat": 10},
    "Crispy Noodles": {"protein": 5, "carbs": 50, "fat": 10},
    "Egg Noodle In Chicken Yellow Curry": {"protein": 10, "carbs": 35, "fat": 15},
    "coconut milk soup": {"protein": 4, "carbs": 10, "fat": 15},
    "pho": {"protein": 15, "carbs": 45, "fat": 10},
    "Hue beef rice vermicelli soup": {"protein": 10, "carbs": 40, "fat": 5},
    "Vermicelli noodles with snails": {"protein": 5, "carbs": 45, "fat": 1},
    "Fried spring rolls": {"protein": 4, "carbs": 20, "fat": 15},
    "Steamed rice roll": {"protein": 3, "carbs": 30, "fat": 2},
    "Shrimp patties": {"protein": 10, "carbs": 10, "fat": 10},
    "ball shaped bun with pork": {"protein": 10, "carbs": 20, "fat": 10},
    "Coconut milk-flavored crepes with shrimp and beef": {"protein": 12, "carbs": 25, "fat": 15},
    "Small steamed savory rice pancake": {"protein": 3, "carbs": 20, "fat": 2},
    "Glutinous Rice Balls": {"protein": 3, "carbs": 40, "fat": 1},
    "loco moco": {"protein": 20, "carbs": 35, "fat": 25},
    "haupia": {"protein": 1, "carbs": 20, "fat": 10},
    "malasada": {"protein": 4, "carbs": 40, "fat": 20},
    "laulau": {"protein": 20, "carbs": 5, "fat": 15},
    "spam musubi": {"protein": 10, "carbs": 40, "fat": 10},
    "oxtail soup": {"protein": 15, "carbs": 5, "fat": 10},
    "adobo": {"protein": 20, "carbs": 10, "fat": 15},
    "lumpia": {"protein": 5, "carbs": 20, "fat": 10},
    "brownie": {"protein": 3, "carbs": 50, "fat": 20},
    "churro": {"protein": 3, "carbs": 30, "fat": 15},
    "jambalaya": {"protein": 15, "carbs": 40, "fat": 15},
    "nasi goreng": {"protein": 10, "carbs": 50, "fat": 15},
    "ayam goreng": {"protein": 15, "carbs": 10, "fat": 20},
    "ayam bakar": {"protein": 20, "carbs": 5, "fat": 15},
    "bubur ayam": {"protein": 5, "carbs": 30, "fat": 5},
    "gulai": {"protein": 10, "carbs": 10, "fat": 10},
    "laksa": {"protein": 10, "carbs": 40, "fat": 15},
    "mie ayam": {"protein": 8, "carbs": 45, "fat": 10},
    "mie goreng": {"protein": 7, "carbs": 50, "fat": 15},
    "nasi campur": {"protein": 10, "carbs": 45, "fat": 10},
    "nasi padang": {"protein": 15, "carbs": 40, "fat": 15},
    "nasi uduk": {"protein": 5, "carbs": 40, "fat": 10},
    "babi guling": {"protein": 25, "carbs": 5, "fat": 20},
    "kaya toast": {"protein": 5, "carbs": 40, "fat": 10},
    "bak kut teh": {"protein": 20, "carbs": 5, "fat": 15},
    "curry puff": {"protein": 5, "carbs": 25, "fat": 15},
    "chow mein": {"protein": 8, "carbs": 45, "fat": 10},
    "zha jiang mian": {"protein": 15, "carbs": 45, "fat": 15},
    "kung pao chicken": {"protein": 20, "carbs": 10, "fat": 20},
    "crullers": {"protein": 4, "carbs": 35, "fat": 20},
    "eggplant with garlic sauce": {"protein": 3, "carbs": 10, "fat": 5},
    "three cup chicken": {"protein": 25, "carbs": 5, "fat": 20},
    "bean curd family style": {"protein": 10, "carbs": 5, "fat": 10},
    "salt & pepper fried shrimp with shell": {"protein": 20, "carbs": 10, "fat": 15},
    "baked salmon": {"protein": 25, "carbs": 0, "fat": 10},
    "braised pork meat ball with napa cabbage": {"protein": 20, "carbs": 5, "fat": 20},
    "winter melon soup": {"protein": 5, "carbs": 5, "fat": 2},
    "steamed spareribs": {"protein": 20, "carbs": 5, "fat": 20},
    "chinese pumpkin pie": {"protein": 3, "carbs": 25, "fat": 10},
    "eight treasure rice": {"protein": 5, "carbs": 40, "fat": 5},
    "hot & sour soup": {"protein": 5, "carbs": 5, "fat": 5}
}


